### PR TITLE
Ignore no bytes transferred if file checks are increasing

### PR DESCRIPTION
**Pull request by herodev1337**
[x] Ignore no bytes transferred if file checks are increasing
The dead_transfer_counter only counts up when there are no bytes copied and the "file checking" counter stays the same. When copying many files, rclone checks for already existing files for a very long time. This can trigger the Service Account switch falsely 

[x] Fix gen_sa_accounts.py not filtering dead projects

### CODE REVIEW

**Comment by williamjohnstone** [comment]
I apologise for the delay, I just saw this, will review it now

**Comment by williamjohnstone** [comment]
Please can you add your changes to the changelog, then I'll get this merged.

**Comment by herodev1337** [comment]
Hey there :)

I will add the things to the changelog. Im sure im committing again soon

Have a nice day ^^

**Comment by williamjohnstone** [comment]
Alright, thank you for your contributions! :)

**Pull request merged**
